name: publish

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '6.0.x' ]

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test
        run: dotnet test --no-restore --verbosity normal
      - name: Publish Windows
        run: dotnet publish ./src/DatabaseBenchmark/DatabaseBenchmark.csproj --no-restore -c Release -r win-x64 --self-contained true
      - name: Publish Linux
        run: dotnet publish ./src/DatabaseBenchmark/DatabaseBenchmark.csproj --no-restore -c Release -r linux-x64 --self-contained true
      - name: Publish OSX
        run: dotnet publish ./src/DatabaseBenchmark/DatabaseBenchmark.csproj --no-restore -c Release -r osx-x64 --self-contained true
      - name: Upload Windows artifacts
        uses: actions/upload-artifact@v3
        with:
          name: DatabaseBenchmark-win-x64.zip
          path: src/DatabaseBenchmark/bin/Release/net6.0/win-x64/publish
      - name: Upload Linux artifacts
        uses: actions/upload-artifact@v3
        with:
          name: DatabaseBenchmark-linux-x64.zip
          path: src/DatabaseBenchmark/bin/Release/net6.0/linux-x64/publish
      - name: Upload OSX artifacts
        uses: actions/upload-artifact@v3
        with:
          name: DatabaseBenchmark-osx-x64.zip
          path: src/DatabaseBenchmark/bin/Release/net6.0/osx-x64/publish